import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css';
import Footer from '../components/Footer';
import NavbarSecond from '../components/NavbarSecond';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
}

export default function SecondLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <div>
        <NavbarSecond />
        {children}
        <Footer/>
    </div>
  )
}
